name: test-mysql

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-mysql:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.9]
        django-version: [2.2.13, 3.0.7, 3.1.2, 3.2.4]
        include:
          - python-version: "3.10"
            django-version: "4.0.4"

    env:
      MYSQL_PASSWORD: mysql
      MYSQL_USER: mysql
      MYSQL_DATABASE: test_db
      MYSQL_HOST: 127.0.0.1
      TEST_WITH_MYSQL: true

    services:
      mysql:
        image: mysql
        ports: ['3306:3306']
        env:
          MYSQL_PASSWORD: mysql
          MYSQL_ROOT_PASSWORD: mysql
          MYSQL_USER: mysql
          MYSQL_DATABASE: test_db
        options: >-
          --health-cmd "mysqladmin ping"
          --health-interval 10s
          --health-timeout 10s
          --health-retries 5

    steps:
      - uses: actions/checkout@v1
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install tooling
        run: |
          python -mpip install poetry codecov
      - name: Install mysqlclient
        run: |
          poetry add mysqlclient
      - name: Install dependencies
        run: |
          poetry install
      - name: Setup Django ${{ matrix.django-version }}
        run: |
          poetry run pip install django==${{ matrix.django-version }}
      - name: Lint with flake
        run: |
          poetry run flake8 django_hashids
      - name: Test with pytest
        run: |
          poetry run py.test --cov=./django_hashids/ --no-migrations
      - name: Upload coverage to codecov
        run: |
          codecov
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
