name: test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-20.04
    strategy:
      max-parallel: 4
      matrix:
        python-version: ["3.12"]
        django-version: ["4.2.9", "5.0.1"]
        include:
          - python-version: "3.8"
            django-version: "1.11.28"
          - python-version: "3.9"
            django-version: "2.2.13"
          - python-version: "3.9"
            django-version: "3.2.4"
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install tooling
        run: |
          python -mpip install poetry codecov; python -mpip install six
      - name: Install dependencies
        run: |
          poetry install --with dev
      - name: Setup Django ${{ matrix.django-version }}
        run: |
          poetry run pip install django==${{ matrix.django-version }}
      - name: Lint with flake
        run: |
          poetry run flake8 django_hashids
      - name: Test with pytest
        run: |
          poetry run py.test --cov=./django_hashids/
      - name: Upload coverage to codecov
        run: |
          codecov
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
